os: linux
services: docker

before_install:
  - make docker-pull
  - make info

notifications:
  email:
    on_success: change
    on_failure: change

addons:
  apt:
    packages:
    - make

install:
  - make build

script:
  - make check test

after_success:
  - make covr
